version: '3.8'
services:
    db:
        image: 'postgres:13.4-alpine'
        container_name: 'database'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - '${DB_PORT}:5432'
        networks:
            - shopper
    web:
        image: 'nginx:alpine'
        container_name: 'web'
        working_dir: /application
        restart: always
        tty: true
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '${APP_PORT}:80'
        depends_on:
            - php
        networks:
            - shopper

    php:
        build: phpdocker/php-fpm
        container_name: 'php'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
        depends_on:
            - db
        networks:
            - shopper

networks:
  shopper:
    name: shopper
    driver: bridge
